# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: allallem <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/22 16:48:55 by allallem          #+#    #+#              #
#    Updated: 2018/01/15 09:48:06 by allallem         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=libft.a
.c= ft_atoi.c ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint.c ft_itoa.c ft_memalloc.c ft_memccpy.c ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memdel.c ft_memmove.c ft_memset.c ft_putchar.c ft_putchar_fd.c ft_putendl.c ft_putendl_fd.c ft_putnbr.c ft_putnbr_fd.c ft_putstr.c ft_putstr_fd.c ft_strcat.c ft_strchr.c ft_strcmp.c ft_strclr.c ft_strcpy.c ft_strdel.c ft_strdup.c ft_strequ.c ft_striteri.c ft_striter.c ft_strlcat.c ft_strmapi.c ft_strjoin.c ft_strlen.c ft_strncat.c ft_strncmp.c ft_strmap.c ft_strncpy.c ft_strnequ.c ft_strnew.c ft_strrchr.c ft_strnstr.c ft_strstr.c ft_strsplit.c ft_strsub.c ft_strtrim.c ft_tolower.c ft_toupper.c ft_lstadd.c ft_lstdel.c ft_lstdelone.c ft_lstiter.c ft_lstmap.c ft_lstnew.c ft_splitlist.c ft_printlist.c ft_sqrt.c ft_strchr_one_more.c ft_sizeoflonglongint.c ft_putaddress.c ft_putoctal.c ft_strstr_int.c ft_atoi_longlongint.c ft_putnbr_spe.c ft_strlen_longlong.c
.o=$(.c:.c=.o)
CC= gcc
CFLAGS= -Werror -Wextra -Wall
DEL= rm -f

all:$(NAME)

re:fclean all

$(NAME):$(.o)
	@ar rc $(NAME) $(.o)
fclean:clean
	@$(DEL) $(NAME)

clean:
	@$(DEL) $(.o)
